stages:
  - test
  - build
  - integration

sudo: required

jobs:
  include:
    - stage: test
      language: go
      go: "1.16"
      script:
        - make install-kubebuilder KUBEBUILDER_INSTALL_DIR=/tmp/kubebuilder
        - export TEST_ASSET_KUBECTL=/tmp/kubebuilder/bin/kubectl
        - export TEST_ASSET_KUBE_APISERVER=/tmp/kubebuilder/bin/kube-apiserver
        - export TEST_ASSET_ETCD=/tmp/kubebuilder/bin/etcd
        - make test

    - stage: build
      if: type == pull_request
      branches:
        except:
          - master
      language: bash
      sudo: required
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t shipasoftware/ketch:$TRAVIS_COMMIT .
        - docker push shipasoftware/ketch:$TRAVIS_COMMIT

    - stage: cli_test
      sudo: required
      language: go
      go: 1.16.x
      services:
        - docker
      provider: script
      env:
        - KETCH_EXECUTABLE_PATH="$TRAVIS_BUILD_DIR/bin/ketch"
      script:
        - bash cli_tests/install_kubectl.sh
        - bash cli_tests/install_minikube.sh
        - bash cli_tests/install_bats.sh
        - bash cli_tests/install_ketch.sh
        - $TRAVIS_BUILD_DIR/bin/ketch help
        - pwd
        - echo $TRAVIS_BUILD_DIR
        - go test ./cli_tests/... -tags integration